GET http://localhost:3333/courses?id=1&page=2

###

POST http://localhost:3333/courses

{
	"name": "Leo"
}

###

DELETE http://localhost:3333/courses/1

###
PUT http://localhost:3333/courses/1

###

DELETE http://localhost:3333/courses/1